global:
  resolve_timeout: 5m

route:
  receiver: "telegram-alerts"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "telegram-alerts"
    telegram_configs:
      - bot_token: "TELEGRAM_BOT_TOKEN"
        chat_id: -123456789
        message: |
          ðŸš¨ ALERT ðŸš¨
          {{ range .Alerts }}
          ðŸ”¹ Alert: {{ .Annotations.summary }}
          ðŸ”¹ Description: {{ .Annotations.description }}
          ðŸ”¹ Severity: {{ .Labels.severity }}
          {{ end }}
