# name: Deploying with AWS

# on:
#   workflow_dispatch: 
#   workflow_run:
#     workflows: ["CI Pipeline and build_push"]  # Name of the previous workflow
#     types:
#       - completed      
  
# env:
#   PRIVATE_KEY: ${{ secrets.RSA_KEY_FOR_APP_EC2 }}
#   INSTANCE_IP: ${{ vars.INSTANCE_IP }}
  

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#         - name: Checkout repository
#           uses: actions/checkout@v4


#         - name: SSH into AWS and deploy docker image
#           uses: appleboy/ssh-action@master
#           with:
#             host: ${{ env.INSTANCE_IP }}
#             username: ec2-user
#             key: ${{ secrets.RSA_KEY_FOR_APP_EC2 }}
#             script: |
             


 






      
